pub mod register_player;

// RegisterPlayer
// Attack {
//     village_id: u32,
//     army: Army,
//     cata_targets: CataTargets,
//     defender_map_id: u32,
// },
// Raid,
// Reinforce,
// ReturnArmy,
// SendMerchant,
// ReturnMerchant,
// TrainBarracksUnit,
// TrainStableUnit,
// TrainWorkshopUnit,
// TrainExpansionUnit,
// TrainTrapperUnit,
// TrainGreatBarracksUnit,
// TrainGreatStableUnit,
// TrainGreatWorkshopUnit,
// ResearchAcademy,
// ResearchSmithy,
// StartTownHallCelebration,
// StartBreweryCelebration,
