[alias]
c = "check"

t = "test"

tt = "test -q"

nt = "nextest run --workspace --show-progress only"
ntq = "nextest run --workspace -j1 --cargo-quiet --show-progress only"

# coverage tests
tc = "tarpaulin -p parabellum_server --release"

# show output
tnc = "test -- --nocapture"
