pub mod buildings;
mod home;
mod login;
mod map;
mod map_field;
mod map_field_found_confirmation;
pub mod player;
mod register;
mod reports;
mod resources;
pub mod stats;
mod village;

pub use home::HomePage;
pub use login::LoginPage;
pub use map::MapPage;
pub use map_field::{MapFieldOasisPage, MapFieldValleyPage, MapFieldVillagePage};
pub use map_field_found_confirmation::FoundVillageConfirmationPage;
pub use player::PlayerProfilePage;
pub use register::RegisterPage;
pub use reports::{BattleReportPage, GenericReportPage, ReinforcementReportPage, ReportsPage};
pub use resources::ResourcesPage;
pub use stats::StatsPage;
pub use village::VillagePage;
